import { Header } from '@/components';
import type { Metadata } from 'next';
import { Providers } from '@/providers/Providers';

import './globals.css';

export const metadata: Metadata = {
  title: 'News App',
  description: 'Generated by Gismo dev',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <Providers>
        <body className="bg-gray-100 dark:bg-zinc-900 transition-all">
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
